version: '3.8'
networks:
  ucbnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.20.0.0/16"
          gateway: "10.20.0.1"
services:
  #node-2:
  #  image: laboratoriov6
  #  ports:
  #    - 8082:80  
  #  networks:
  #    - ucbnet
  mysql-server:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=twitter
      - MYSQL_USER=victor
      - MYSQL_PASSWORD=0
      - MYSQL_ROOT_PASSWORD=0
    networks:
      - ucbnet

  node-1:
    depends_on:
      - mysql-server
    command: bash -c 'while !</dev/tcp/mysql-server/3306; do sleep 2; done; npm start'
    image: laboratoriov7
    ports:
      - 8081:80
    networks: 
      - ucbnet